import sys
from PyQt5 import QtCore, QtGui, QtWidgets

#etudiants
from ajout import Ui_Form as ajoutForm
from supprimer import Ui_Form as supprimerForm
from supprimer_section import Ui_Form as supprimer_sectionForm
from supprimer_niveau import Ui_Form as supprimer_niveauForm
from supprimer_section_niveau import Ui_Form as supprimer_section_niveauForm
from modifier_adresse import Ui_Form as modifier_adresseForm
from modifier_mail import Ui_Form as modifier_mailForm
from modifier_tel import Ui_Form as modifier_telForm
from recherche_niveau import Ui_Form as recherche_niveauForm
from recherche_num_inscr import Ui_Form as recherche_numForm
from recherche_section import Ui_Form as recherche_sectionForm
from recherche_section_niveau import Ui_Form as recherche_section_niveauForm


#matiere
from ajout_matiere import Ui_Form as ajout_matiereForm
from modifier_coefficient_matiere import Ui_Form as modifier_coefficient_matiereForm
from modifier_nom_matiere import Ui_Form as modifie_nom_matiereForm
from recherche_code_matiere import Ui_Form as recherche_code_matiereForm
from recherche_section_matiere import Ui_Form as recherche_section_matiereForm
from recherche_section_semestre_matiere import Ui_Form as recherche_section_semestre_matiereForm
from supprimer_matiere import Ui_Form as supprimer_matiereForm

#note
from  ajout_note import Ui_Form as ajout_noteForm
from modifier_note import Ui_Form as modifier_noteForm
from recherche_num_inscr_note import Ui_Form as recherche_num_inscr_noteForm
from recherche_num_semestre_NOTE import Ui_Form as recherche_num_semestre_NOTEForm
from recherche_section_niveau_note import Ui_Form as recherche_section_niveau_noteForm
from supprimer_note import Ui_Form as supprimer_noteForm

#etudiant={}

class Ui_MainWindow(QtWidgets.QMainWindow):
   def __init__(self):
        super(Ui_MainWindow,self).__init__()
        self.setWindowTitle("Gestion des notes des etudiants")
        self.inst=institut
        self.resize(1060, 631)
        self.setStyleSheet("alternate-background-color: rgb(61, 85, 55);")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(910, 170, 131, 131))
        self.label.setStyleSheet("background-color: rgb(137, 33, 255);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../téléchargement.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(750, 500, 381, 71))
        self.label_3.setStyleSheet("font: 75 11pt \"Poppins\";")
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 150, 1071, 191))
        self.textBrowser.setStyleSheet("font: 26pt \"Bernard MT Condensed\";")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(670, 460, 461, 61))
        self.label_2.setStyleSheet("font: 75 italic 17pt \"MS Sans Serif\";\n"
"")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-10, -10, 1071, 631))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.textBrowser.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 26))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuMenageStudent = QtWidgets.QMenu(self.menubar)
        self.menuMenageStudent.setObjectName("menuMenageStudent")
        self.menuUpdateStudent = QtWidgets.QMenu(self.menuMenageStudent)
        self.menuUpdateStudent.setObjectName("menuUpdateStudent")
        self.menuDeleteStudent = QtWidgets.QMenu(self.menuUpdateStudent)
        self.menuDeleteStudent.setObjectName("menuDeleteStudent")
        self.MenuModifyStudent = QtWidgets.QMenu(self.menuUpdateStudent)
        self.MenuModifyStudent.setObjectName("MenuModifyStudent")
        self.menuSearchAndPrint = QtWidgets.QMenu(self.menuMenageStudent)
        self.menuSearchAndPrint.setObjectName("menuSearchAndPrint")
        self.menuMenageSubjects = QtWidgets.QMenu(self.menubar)
        self.menuMenageSubjects.setObjectName("menuMenageSubjects")
        self.menuUpdate = QtWidgets.QMenu(self.menuMenageSubjects)
        self.menuUpdate.setObjectName("menuUpdate")
        self.menuModifySubjectsData = QtWidgets.QMenu(self.menuUpdate)
        self.menuModifySubjectsData.setObjectName("menuModifySubjectsData")
        self.menuSearchAndPrint2 = QtWidgets.QMenu(self.menuMenageSubjects)
        self.menuSearchAndPrint2.setObjectName("menuSearchAndPrint2")
        self.menuMenageMarks = QtWidgets.QMenu(self.menubar)
        self.menuMenageMarks.setObjectName("menuMenageMarks")
        self.menuUpdate2 = QtWidgets.QMenu(self.menuMenageMarks)
        self.menuUpdate2.setObjectName("menuUpdate2")
        self.menuSearchAndPrint = QtWidgets.QMenu(self.menuMenageMarks)
        self.menuSearchAndPrint.setObjectName("menuSearchAndPrint")
        self.menuCountAndShow = QtWidgets.QMenu(self.menubar)
        self.menuCountAndShow.setObjectName("menuCountAndShow")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.onAddStudent = QtWidgets.QAction(self)
        self.onAddStudent.setObjectName("onAddStudent")
        self.onDeleteStudentDone = QtWidgets.QAction(self)
        self.onDeleteStudentDone.setObjectName("onDeleteStudentDone")
        self.onDeleteStudentBySectionDone = QtWidgets.QAction(self)
        self.onDeleteStudentBySectionDone.setObjectName("onDeleteStudentBySectionDone")
        self.onDeleteStudentByLevelDone = QtWidgets.QAction(self)
        self.onDeleteStudentByLevelDone.setObjectName("onDeleteStudentByLevelDone")
        self.onDeleteStudentByLevelAndSectionDone = QtWidgets.QAction(self)
        self.onDeleteStudentByLevelAndSectionDone.setObjectName("onDeleteStudentByLevelAndSectionDone")
        self.onPhone = QtWidgets.QAction(self)
        self.onPhone.setObjectName("onPhone")
        self.onMail = QtWidgets.QAction(self)
        self.onMail.setObjectName("onMail")
        self.onAddress = QtWidgets.QAction(self)
        self.onAddress.setObjectName("onAddress")
        self.onShowStudents = QtWidgets.QAction(self)
        self.onShowStudents.setObjectName("onShowStudents")
        self.onSearchById = QtWidgets.QAction(self)
        self.onSearchById.setObjectName("onSearchById")
        self.onSearchBySection = QtWidgets.QAction(self)
        self.onSearchBySection.setObjectName("onSearchBySection")
        self.onSearchBySectionAndLevel = QtWidgets.QAction(self)
        self.onSearchBySectionAndLevel.setObjectName("onSearchBySectionAndLevel")
        self.onSearchByLevel = QtWidgets.QAction(self)
        self.onSearchByLevel.setObjectName("onSearchByLevel")
        self.onAddNewSubject = QtWidgets.QAction(self)
        self.onAddNewSubject.setObjectName("onAddNewSubject")
        self.onDeleteSubject = QtWidgets.QAction(self)
        self.onDeleteSubject.setObjectName("onDeleteSubject")
        self.onName = QtWidgets.QAction(self)
        self.onName.setObjectName("onName")
        self.OnCoefficient = QtWidgets.QAction(self)
        self.OnCoefficient.setObjectName("OnCoefficient")
        self.onShowSubjects = QtWidgets.QAction(self)
        self.onShowSubjects.setObjectName("onShowSubjects")
        self.onSearchByCode = QtWidgets.QAction(self)
        self.onSearchByCode.setObjectName("onSearchByCode")
        self.onSearchBySection2 = QtWidgets.QAction(self)
        self.onSearchBySection2.setObjectName("onSearchBySection2")
        self.onSeachByTermAndSection = QtWidgets.QAction(self)
        self.onSeachByTermAndSection.setObjectName("onSeachByTermAndSection")
        self.onAddNewMark = QtWidgets.QAction(self)
        self.onAddNewMark.setObjectName("onAddNewMark")
        self.onDeleteMark = QtWidgets.QAction(self)
        self.onDeleteMark.setObjectName("onDeleteMark")
        self.onModifyDataMark = QtWidgets.QAction(self)
        self.onModifyDataMark.setObjectName("onModifyDataMark")
        self.onShowMarks = QtWidgets.QAction(self)
        self.onShowMarks.setObjectName("onShowMarks")
        self.onSearchMarkByID = QtWidgets.QAction(self)
        self.onSearchMarkByID.setObjectName("onSearchMarkByID")
        self.onSearchBySectionAndLevel2 = QtWidgets.QAction(self)
        self.onSearchBySectionAndLevel2.setObjectName("onSearchBySectionAndLevel2")
        self.onSearchMarkByIDAndTerm = QtWidgets.QAction(self)
        self.onSearchMarkByIDAndTerm.setObjectName("onSearchMarkByIDAndTerm")
        self.onBillByStudent = QtWidgets.QAction(self)
        self.onBillByStudent.setObjectName("onBillByStudent")
        self.onBillByTerm = QtWidgets.QAction(self)
        self.onBillByTerm.setObjectName("onBillByTerm")
        self.onSuccBySection = QtWidgets.QAction(self)
        self.onSuccBySection.setObjectName("onSuccBySection")
        self.onFailBySection = QtWidgets.QAction(self)
        self.onFailBySection.setObjectName("onFailBySection")
        self.onSuccByISIMM = QtWidgets.QAction(self)
        self.onSuccByISIMM.setObjectName("onSuccByISIMM")
        self.onFailByISIMM = QtWidgets.QAction(self)
        self.onFailByISIMM.setObjectName("onFailByISIMM")
        self.onFailBySection2 = QtWidgets.QAction(self)
        self.onFailBySection2.setObjectName("onFailBySection2")
        self.onAverageBySEction = QtWidgets.QAction(self)
        self.onAverageBySEction.setObjectName("onAverageBySEction")
        self.onSaveStudents = QtWidgets.QAction(self)
        self.onSaveStudents.setObjectName("onSaveStudents")
        self.onBackupStudents = QtWidgets.QAction(self)
        self.onBackupStudents.setObjectName("onBackupStudents")
        self.onSaveSubjects = QtWidgets.QAction(self)
        self.onSaveSubjects.setObjectName("onSaveSubjects")
        self.onBackUpSubjects = QtWidgets.QAction(self)
        self.onBackUpSubjects.setObjectName("onBackUpSubjects")
        self.onSaveMarks = QtWidgets.QAction(self)
        self.onSaveMarks.setObjectName("onSaveMarks")
        self.onBackUpMarks = QtWidgets.QAction(self)
        self.onBackUpMarks.setObjectName("onBackUpMarks")
        self.menuDeleteStudent.addAction(self.onDeleteStudentDone)
        self.menuDeleteStudent.addAction(self.onDeleteStudentBySectionDone)
        self.menuDeleteStudent.addAction(self.onDeleteStudentByLevelDone)
        self.menuDeleteStudent.addAction(self.onDeleteStudentByLevelAndSectionDone)
        self.MenuModifyStudent.addAction(self.onPhone)
        self.MenuModifyStudent.addAction(self.onMail)
        self.MenuModifyStudent.addAction(self.onAddress)
        self.menuUpdateStudent.addAction(self.onAddStudent)
        self.menuUpdateStudent.addAction(self.menuDeleteStudent.menuAction())
        self.menuUpdateStudent.addAction(self.MenuModifyStudent.menuAction())
        self.menuSearchAndPrint.addAction(self.onShowStudents)
        self.menuSearchAndPrint.addAction(self.onSearchById)
        self.menuSearchAndPrint.addAction(self.onSearchBySection)
        self.menuSearchAndPrint.addAction(self.onSearchBySectionAndLevel)
        self.menuSearchAndPrint.addAction(self.onSearchByLevel)
        self.menuMenageStudent.addAction(self.menuUpdateStudent.menuAction())
        self.menuMenageStudent.addAction(self.menuSearchAndPrint.menuAction())
        self.menuModifySubjectsData.addAction(self.onName)
        self.menuModifySubjectsData.addAction(self.OnCoefficient)
        self.menuUpdate.addAction(self.onAddNewSubject)
        self.menuUpdate.addAction(self.onDeleteSubject)
        self.menuUpdate.addAction(self.menuModifySubjectsData.menuAction())
        self.menuSearchAndPrint2.addAction(self.onShowSubjects)
        self.menuSearchAndPrint2.addAction(self.onSearchByCode)
        self.menuSearchAndPrint2.addAction(self.onSearchBySection2)
        self.menuSearchAndPrint2.addAction(self.onSeachByTermAndSection)
        self.menuMenageSubjects.addAction(self.menuUpdate.menuAction())
        self.menuMenageSubjects.addAction(self.menuSearchAndPrint2.menuAction())
        self.menuUpdate2.addAction(self.onAddNewMark)
        self.menuUpdate2.addAction(self.onDeleteMark)
        self.menuUpdate2.addAction(self.onModifyDataMark)
        self.menuSearchAndPrint.addAction(self.onShowMarks)
        self.menuSearchAndPrint.addAction(self.onSearchMarkByID)
        self.menuSearchAndPrint.addAction(self.onSearchBySectionAndLevel2)
        self.menuSearchAndPrint.addAction(self.onSearchMarkByIDAndTerm)
        self.menuMenageMarks.addAction(self.menuUpdate2.menuAction())
        self.menuMenageMarks.addAction(self.menuSearchAndPrint.menuAction())
        self.menuCountAndShow.addAction(self.onBillByStudent)
        self.menuCountAndShow.addAction(self.onBillByTerm)
        self.menuCountAndShow.addAction(self.onSuccBySection)
        self.menuCountAndShow.addAction(self.onFailBySection)
        self.menuCountAndShow.addAction(self.onSuccByISIMM)
        self.menuCountAndShow.addAction(self.onFailByISIMM)
        self.menuCountAndShow.addAction(self.onFailBySection2)
        self.menuCountAndShow.addAction(self.onAverageBySEction)
        self.menuSave.addAction(self.onSaveStudents)
        self.menuSave.addAction(self.onBackupStudents)
        self.menuSave.addAction(self.onSaveSubjects)
        self.menuSave.addAction(self.onBackUpSubjects)
        self.menuSave.addAction(self.onSaveMarks)
        self.menuSave.addAction(self.onBackUpMarks)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuMenageStudent.menuAction())
        self.menubar.addAction(self.menuMenageSubjects.menuAction())
        self.menubar.addAction(self.menuMenageMarks.menuAction())
        self.menubar.addAction(self.menuCountAndShow.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.retranslateUi(self)

        #connecter les fenetres
        self.onAddStudent.triggered.connect(self.ajoutEtud)
        self.onDeleteStudentDone.triggered.connect(self.supprimer)
        self.onDeleteStudentBySectionDone.triggered.connect(self.supprimer_section)
        self.onDeleteStudentByLevelDone.triggered.connect(self.supprimer_niveau)
        self.onDeleteStudentByLevelAndSectionDone.triggered.connect(self.supprimer_section_niveau)
        self.retranslateUi(self)
        self.onPhone.triggered.connect(self.modifier_tel)
        self.onAddress.triggered.connect(self.modifier_adresse)
        self.onMail.triggered.connect(self.modifier_mail)
        self.onSearchById.triggered.connect(self.recherche_num)
        self.onSearchBySection.triggered.connect(self.recherche_section)
        self.onSearchBySectionAndLevel.triggered.connect(self.recherche_section_niveau)
        self.onSearchByLevel.triggered.connect(self.recherche_niveau)
        self.onAddNewSubject.triggered.connect(self.ajout_matiere)
        self.onDeleteSubject.triggered.connect(self.supprimer_matiere)
        self.onName.triggered.connect(self.modifier_nom_matiere)
        self.OnCoefficient.triggered.connect(self.modifier_coefficient_matiere)
        self.onSearchByCode.triggered.connect(self.recherche_code_matiere)
        self.onSearchBySection2.triggered.connect(self.recherche_section_matiere)
        self.onSeachByTermAndSection.triggered.connect(self.recherche_section_semestre_matiere)
        self.onAddNewMark.triggered.connect(self.ajout_note)
        self.onModifyDataMark.triggered.connect(self.modifier_note)
        self.onSearchMarkByID.triggered.connect(self.recherche_num_inscr_note)
        self.onSearchMarkByIDAndTerm.triggered.connect(self.rechercher_num_semestre_note)
        self.onSearchBySectionAndLevel2.triggered.connect(self.recherche_section_niveau_note)
        self.onDeleteMark.triggered.connect(self.supprimer_note)




   def retranslateUi(self,MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "ANNEE UNIVERSITAIRE :2021/2022"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bernard MT Condensed\'; font-size:26pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Poppins\'; font-size:36pt; font-weight:600;color:#fff; font-style:italic; color:#750000;\">MINI PROJET : GESTION DES     NOTES  DES      ETUDIANTS</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Realise par : XXXX"))
        self.menuHome.setTitle(_translate("MainWindow", "ACCUEIL"))
        self.menuMenageStudent.setTitle(_translate("MainWindow", "Gestion des etudiants"))
        self.menuUpdateStudent.setTitle(_translate("MainWindow", "mise a jour des etudiants"))
        self.menuDeleteStudent.setTitle(_translate("MainWindow", "supprimer etudiant"))
        self.MenuModifyStudent.setTitle(_translate("MainWindow", "modifier etudiant"))
        self.menuSearchAndPrint.setTitle(_translate("MainWindow", "recherche et affichage"))
        self.menuMenageSubjects.setTitle(_translate("MainWindow", "Gestion des matieres"))
        self.menuUpdate.setTitle(_translate("MainWindow", "mise a jour"))
        self.menuModifySubjectsData.setTitle(_translate("MainWindow", "modifier les donnée d\'une matiere"))
        self.menuSearchAndPrint2.setTitle(_translate("MainWindow", "recherche et affichage"))
        self.menuMenageMarks.setTitle(_translate("MainWindow", "Gestion des notes"))
        self.menuUpdate2.setTitle(_translate("MainWindow", "mise a jour"))
        self.menuSearchAndPrint.setTitle(_translate("MainWindow", "recherche , affichage"))
        self.menuCountAndShow.setTitle(_translate("MainWindow", "Calcul et affichage"))
        self.menuSave.setTitle(_translate("MainWindow", "Enreg.et Recup.Fichiers"))
        self.onAddStudent.setText(_translate("MainWindow", "ajouter etudiant"))
        self.onDeleteStudentDone.setText(_translate("MainWindow", "suppression etudiant donnée"))
        self.onDeleteStudentBySectionDone.setText(_translate("MainWindow", "suppression des etudiants d\'une section donnée"))
        self.onDeleteStudentByLevelDone.setText(_translate("MainWindow", "suppression des etudiants d\'un niveau donné"))
        self.onDeleteStudentByLevelAndSectionDone.setText(_translate("MainWindow", "suppression des etudiants d\'un niveau donné et d\'une section donnée"))
        self.onPhone.setText(_translate("MainWindow", "telephone"))
        self.onMail.setText(_translate("MainWindow", "mail"))
        self.onAddress.setText(_translate("MainWindow", "adresse"))
        self.onShowStudents.setText(_translate("MainWindow", "contenu du dictionnaire etudiant"))
        self.onSearchById.setText(_translate("MainWindow", "recherche par numero d\'inscription"))
        self.onSearchBySection.setText(_translate("MainWindow", "recherche par section"))
        self.onSearchBySectionAndLevel.setText(_translate("MainWindow", "recherche par section et niveau"))
        self.onSearchByLevel.setText(_translate("MainWindow", "recherche par niveau"))
        self.onAddNewSubject.setText(_translate("MainWindow", "ajouter une nouvelle matiere"))
        self.onDeleteSubject.setText(_translate("MainWindow", "supprimer une matiere"))
        self.onName.setText(_translate("MainWindow", "nom"))
        self.OnCoefficient.setText(_translate("MainWindow", "coefficient"))
        self.onShowSubjects.setText(_translate("MainWindow", "contenu du dictionnaire matiere"))
        self.onSearchByCode.setText(_translate("MainWindow", "recherche par code"))
        self.onSearchBySection2.setText(_translate("MainWindow", "recherche par section"))
        self.onSeachByTermAndSection.setText(_translate("MainWindow", "recherche par semestre et section"))
        self.onAddNewMark.setText(_translate("MainWindow", "ajouter une nouvelle note"))
        self.onDeleteMark.setText(_translate("MainWindow", "supprimer une note"))
        self.onModifyDataMark.setText(_translate("MainWindow", "modifier les donnes d\'une note"))
        self.onShowMarks.setText(_translate("MainWindow", "contenu du dictionnaire notes"))
        self.onSearchMarkByID.setText(_translate("MainWindow", "recherche par numero inscription"))
        self.onSearchBySectionAndLevel2.setText(_translate("MainWindow", "recherche par section et niveau"))
        self.onSearchMarkByIDAndTerm.setText(_translate("MainWindow", "recherche par numero inscription et semestre"))
        self.onBillByStudent.setText(_translate("MainWindow", "bulletin de note d\'un etudiant"))
        self.onBillByTerm.setText(_translate("MainWindow", "bulletin de note d\'un etudiant par semestre"))
        self.onSuccBySection.setText(_translate("MainWindow", "etudiants admis d\'une section donnee"))
        self.onFailBySection.setText(_translate("MainWindow", "etudiants redoublants d\'une section donnee"))
        self.onSuccByISIMM.setText(_translate("MainWindow", "etudiants admis de l\'ISIMM"))
        self.onFailByISIMM.setText(_translate("MainWindow", "etudiants redoublants de l\'ISIMM"))
        self.onFailBySection2.setText(_translate("MainWindow", "etudiants redoublants d\'une section donnee"))
        self.onAverageBySEction.setText(_translate("MainWindow", "moyennes des etudiants d\'une section donnee"))
        self.onSaveStudents.setText(_translate("MainWindow", "enregistrement fichier etudiants"))
        self.onBackupStudents.setText(_translate("MainWindow", "recuperation fichiers etudiants"))
        self.onSaveSubjects.setText(_translate("MainWindow", "enregistrement fichier matieres"))
        self.onBackUpSubjects.setText(_translate("MainWindow", "recuperation fichier matieres"))
        self.onSaveMarks.setText(_translate("MainWindow", "enregistrement fichier notes"))
        self.onBackUpMarks.setText(_translate("MainWindow", "recuperation fichier notes"))
#ouvrir fenetre ajout
   def ajoutEtud(self):
       Form = QtWidgets.QDialog()
       ui = ajoutForm()
       ui.setupUi(Form)
       ret = Form.exec_()


   #ouvrir fenetre supprimer
   def supprimer(self):
            Form = QtWidgets.QDialog()
            ui = supprimerForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def supprimer_section(self):
             Form = QtWidgets.QDialog()
             ui = supprimer_sectionForm()
             ui.setupUi(Form)
             ret = Form.exec_()
   def supprimer_niveau(self):
            Form = QtWidgets.QDialog()
            ui = supprimer_niveauForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def supprimer_section_niveau(self):
            Form = QtWidgets.QDialog()
            ui = supprimer_section_niveauForm()
            ui.setupUi(Form)
            ret = Form.exec_()
    #ouvrir fenetre modifier
   def modifier_adresse(self):
            Form = QtWidgets.QDialog()
            ui = modifier_adresseForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def modifier_mail(self):
            Form = QtWidgets.QDialog()
            ui = modifier_mailForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def modifier_tel(self):
            Form = QtWidgets.QDialog()
            ui = modifier_telForm()
            ui.setupUi(Form)
            ret = Form.exec_()
    #affichage et recherche
   def recherche_niveau(self):
            Form = QtWidgets.QDialog()
            ui = recherche_niveauForm()
            ui.setupUi(Form)
            ret = Form.exec_()

   def recherche_section(self):
            Form = QtWidgets.QDialog()
            ui = recherche_sectionForm()
            ui.setupUi(Form)
            ret = Form.exec_()

   def recherche_num(self):
            Form = QtWidgets.QDialog()
            ui = recherche_numForm()
            ui.setupUi(Form)
            ret = Form.exec_()

   def recherche_section_niveau(self):
            Form = QtWidgets.QDialog()
            ui = recherche_section_niveauForm()
            ui.setupUi(Form)
            ret = Form.exec_()


        #gestion des matieres
   def ajout_matiere(self):
            Form = QtWidgets.QDialog()
            ui = ajout_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def modifier_coefficient_matiere(self):
            Form = QtWidgets.QDialog()
            ui = modifier_coefficient_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def modifier_nom_matiere(self):
            Form = QtWidgets.QDialog()
            ui = modifie_nom_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def recherche_code_matiere(self):
            Form = QtWidgets.QDialog()
            ui = recherche_code_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def recherche_section_matiere(self):
            Form = QtWidgets.QDialog()
            ui = recherche_section_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def recherche_section_semestre_matiere(self):
            Form = QtWidgets.QDialog()
            ui = recherche_section_semestre_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def supprimer_matiere(self):
            Form = QtWidgets.QDialog()
            ui = supprimer_matiereForm()
            ui.setupUi(Form)
            ret = Form.exec_()

    #notes
   def ajout_note(self):
            Form = QtWidgets.QDialog()
            ui = ajout_noteForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def modifier_note(self):
            Form = QtWidgets.QDialog()
            ui = modifier_noteForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def recherche_num_inscr_note(self):
            Form = QtWidgets.QDialog()
            ui = recherche_num_inscr_noteForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def rechercher_num_semestre_note(self):
            Form = QtWidgets.QDialog()
            ui = recherche_num_semestre_NOTEForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def recherche_section_niveau_note(self):
            Form = QtWidgets.QDialog()
            ui = recherche_section_niveau_noteForm()
            ui.setupUi(Form)
            ret = Form.exec_()
   def supprimer_note(self):
            Form = QtWidgets.QDialog()
            ui = supprimer_noteForm()
            ui.setupUi(Form)
            ret = Form.exec_()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    ui.show()
    sys.exit(app.exec_())
